# Generated by Django 5.1.5 on 2025-02-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
